// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlataformaDeGestionDeCursosOnline.Infrastructure;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260410234104_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlataformaDeGestionDeCursosOnline.Domain.Entities.Clases.Asistencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdClase")
                        .HasColumnType("uuid")
                        .HasColumnName("IdClase");

                    b.Property<Guid>("IdInscripcionEstudiante")
                        .HasColumnType("uuid")
                        .HasColumnName("IdInscripcionEstudiante");

                    b.Property<bool>("Presente")
                        .HasColumnType("boolean")
                        .HasColumnName("Presente");

                    b.HasKey("Id");

                    b.HasIndex("IdClase");

                    b.HasIndex("IdInscripcionEstudiante");

                    b.ToTable("Asistencias", (string)null);
                });

            modelBuilder.Entity("PlataformaDeGestionDeCursosOnline.Domain.Entities.Clases.Clase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("Estado");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Fecha")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("IdCurso")
                        .HasColumnType("uuid")
                        .HasColumnName("IdCurso");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Material");

                    b.HasKey("Id");

                    b.HasIndex("IdCurso");

                    b.ToTable("Clases", (string)null);
                });

            modelBuilder.Entity("PlataformaDeGestionDeCursosOnline.Domain.Entities.Clases.Consulta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("Descripcion");

                    b.Property<DateTime>("FechaConsulta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaConsulta");

                    b.Property<Guid>("IdClase")
                        .HasColumnType("uuid")
                        .HasColumnName("IdClase");

                    b.Property<Guid>("IdEstudiante")
                        .HasColumnType("uuid")
                        .HasColumnName("IdEstudiante");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Titulo");

                    b.HasKey("Id");

                    b.HasIndex("IdClase");

                    b.HasIndex("IdEstudiante");

                    b.ToTable("Consultas", (string)null);
                });

            modelBuilder.Entity("PlataformaDeGestionDeCursosOnline.Domain.Entities.Cursos.Curso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("Estado");

                    b.Property<Guid>("IdProfesor")
                        .HasColumnType("uuid")
                        .HasColumnName("IdProfesor");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Nombre");

                    b.Property<string>("Temario")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("Temario");

                    b.HasKey("Id");

                    b.HasIndex("IdProfesor");

                    b.ToTable("Cursos", (string)null);
                });

            modelBuilder.Entity("PlataformaDeGestionDeCursosOnline.Domain.Entities.Encuestas.Encuesta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CalificacionCurso")
                        .HasColumnType("integer")
                        .HasColumnName("CalificacionCurso");

                    b.Property<int>("CalificacionDocente")
                        .HasColumnType("integer")
                        .HasColumnName("CalificacionDocente");

                    b.Property<int>("CalificacionMaterial")
                        .HasColumnType("integer")
                        .HasColumnName("CalificacionMaterial");

                    b.Property<string>("Comentarios")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("Comentarios");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreacion");

                    b.Property<Guid>("IdCurso")
                        .HasColumnType("uuid")
                        .HasColumnName("IdCurso");

                    b.Property<Guid?>("IdEstudiante")
                        .HasColumnType("uuid")
                        .HasColumnName("IdEstudiante");

                    b.HasKey("Id");

                    b.HasIndex("IdCurso");

                    b.HasIndex("IdEstudiante");

                    b.ToTable("Encuestas", (string)null);
                });

            modelBuilder.Entity("PlataformaDeGestionDeCursosOnline.Domain.Entities.Examenes.EntregaDelExamen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ComentarioDocente")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("ComentarioDocente");

                    b.Property<DateTime>("FechaEntregado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaEntregado");

                    b.Property<Guid>("IdExamen")
                        .HasColumnType("uuid")
                        .HasColumnName("IdExamen");

                    b.Property<Guid>("IdInscripcionEstudiante")
                        .HasColumnType("uuid")
                        .HasColumnName("IdInscripcionEstudiante");

                    b.Property<decimal?>("Nota")
                        .HasColumnType("numeric")
                        .HasColumnName("Nota");

                    b.Property<string>("Respuesta")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("Respuesta");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("Tipo");

                    b.HasKey("Id");

                    b.HasIndex("IdExamen");

                    b.HasIndex("IdInscripcionEstudiante");

                    b.ToTable("EntregasExamen", (string)null);
                });

            modelBuilder.Entity("PlataformaDeGestionDeCursosOnline.Domain.Entities.Examenes.Examen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaExamenCargado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaExamenCargado");

                    b.Property<DateTime>("FechaLimiteDeEntrega")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaLimiteDeEntrega");

                    b.Property<Guid>("IdCurso")
                        .HasColumnType("uuid")
                        .HasColumnName("IdCurso");

                    b.Property<string>("TemaExamen")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("TemaExamen");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("Tipo");

                    b.HasKey("Id");

                    b.HasIndex("IdCurso");

                    b.ToTable("Examenes", (string)null);
                });

            modelBuilder.Entity("PlataformaDeGestionDeCursosOnline.Domain.Entities.Inscripciones.Inscripcion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("Activa");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaInscripcion");

                    b.Property<Guid>("IdCurso")
                        .HasColumnType("uuid")
                        .HasColumnName("IdCurso");

                    b.Property<Guid>("IdEstudiante")
                        .HasColumnType("uuid")
                        .HasColumnName("IdEstudiante");

                    b.Property<double>("porcentajeAsistencia")
                        .HasColumnType("double precision")
                        .HasColumnName("PorcentajeAsistencia");

                    b.HasKey("Id");

                    b.HasIndex("IdCurso");

                    b.HasIndex("IdEstudiante");

                    b.ToTable("Inscripciones", (string)null);
                });

            modelBuilder.Entity("PlataformaDeGestionDeCursosOnline.Domain.Entities.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Apellido");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Contrasea");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Dni");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Email");

                    b.Property<string>("Especialidad")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Especialidad");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaRegistro")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Nombre");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);

                    b.HasDiscriminator<string>("Rol");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PlataformaDeGestionDeCursosOnline.Domain.Entities.Estudiantes.Estudiante", b =>
                {
                    b.HasBaseType("PlataformaDeGestionDeCursosOnline.Domain.Entities.Usuarios.Usuario");

                    b.HasDiscriminator().HasValue("Estudiante");
                });

            modelBuilder.Entity("PlataformaDeGestionDeCursosOnline.Domain.Entities.Profesores.Profesor", b =>
                {
                    b.HasBaseType("PlataformaDeGestionDeCursosOnline.Domain.Entities.Usuarios.Usuario");

                    b.HasDiscriminator().HasValue("Profesor");
                });

            modelBuilder.Entity("PlataformaDeGestionDeCursosOnline.Domain.Entities.Clases.Asistencia", b =>
                {
                    b.HasOne("PlataformaDeGestionDeCursosOnline.Domain.Entities.Clases.Clase", null)
                        .WithMany()
                        .HasForeignKey("IdClase")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaDeGestionDeCursosOnline.Domain.Entities.Inscripciones.Inscripcion", null)
                        .WithMany()
                        .HasForeignKey("IdInscripcionEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlataformaDeGestionDeCursosOnline.Domain.Entities.Clases.Clase", b =>
                {
                    b.HasOne("PlataformaDeGestionDeCursosOnline.Domain.Entities.Cursos.Curso", null)
                        .WithMany()
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlataformaDeGestionDeCursosOnline.Domain.Entities.Clases.Consulta", b =>
                {
                    b.HasOne("PlataformaDeGestionDeCursosOnline.Domain.Entities.Clases.Clase", null)
                        .WithMany()
                        .HasForeignKey("IdClase")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaDeGestionDeCursosOnline.Domain.Entities.Estudiantes.Estudiante", null)
                        .WithMany()
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlataformaDeGestionDeCursosOnline.Domain.Entities.Cursos.Curso", b =>
                {
                    b.HasOne("PlataformaDeGestionDeCursosOnline.Domain.Entities.Profesores.Profesor", null)
                        .WithMany()
                        .HasForeignKey("IdProfesor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("PlataformaDeGestionDeCursosOnline.Domain.Entities.Cursos.ObjectValues.DateRange", "Duracion", b1 =>
                        {
                            b1.Property<Guid>("CursoId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("Fin")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("FechaFin");

                            b1.Property<DateTime>("Inicio")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("FechaInicio");

                            b1.HasKey("CursoId");

                            b1.ToTable("Cursos");

                            b1.WithOwner()
                                .HasForeignKey("CursoId");
                        });

                    b.Navigation("Duracion")
                        .IsRequired();
                });

            modelBuilder.Entity("PlataformaDeGestionDeCursosOnline.Domain.Entities.Encuestas.Encuesta", b =>
                {
                    b.HasOne("PlataformaDeGestionDeCursosOnline.Domain.Entities.Cursos.Curso", null)
                        .WithMany()
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaDeGestionDeCursosOnline.Domain.Entities.Estudiantes.Estudiante", null)
                        .WithMany()
                        .HasForeignKey("IdEstudiante");
                });

            modelBuilder.Entity("PlataformaDeGestionDeCursosOnline.Domain.Entities.Examenes.EntregaDelExamen", b =>
                {
                    b.HasOne("PlataformaDeGestionDeCursosOnline.Domain.Entities.Examenes.Examen", null)
                        .WithMany()
                        .HasForeignKey("IdExamen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaDeGestionDeCursosOnline.Domain.Entities.Inscripciones.Inscripcion", null)
                        .WithMany()
                        .HasForeignKey("IdInscripcionEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlataformaDeGestionDeCursosOnline.Domain.Entities.Examenes.Examen", b =>
                {
                    b.HasOne("PlataformaDeGestionDeCursosOnline.Domain.Entities.Cursos.Curso", null)
                        .WithMany()
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlataformaDeGestionDeCursosOnline.Domain.Entities.Inscripciones.Inscripcion", b =>
                {
                    b.HasOne("PlataformaDeGestionDeCursosOnline.Domain.Entities.Cursos.Curso", null)
                        .WithMany()
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaDeGestionDeCursosOnline.Domain.Entities.Estudiantes.Estudiante", null)
                        .WithMany()
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlataformaDeGestionDeCursosOnline.Domain.Entities.Usuarios.Usuario", b =>
                {
                    b.OwnsOne("PlataformaDeGestionDeCursosOnline.Domain.Entities.Usuarios.ObjectValues.Direccion", "Direccion", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Altura")
                                .HasColumnType("integer")
                                .HasColumnName("Altura");

                            b1.Property<string>("Calle")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("Calle");

                            b1.Property<string>("Ciudad")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Ciudad");

                            b1.Property<string>("Pais")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Pais");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Direccion")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
