using PlataformaDeGestionDeCursosOnline.Application.Abstractions.Messaging;

namespace PlataformaDeGestionDeCursosOnline.Application.Querys.Inscripciones;

public record ObtenerPorcentajeDeAsistenciaPorCursoQuery(Guid IdInscripcion) : IQuery<double>;