using PlataformaDeGestionDeCursosOnline.Application.Abstractions.Messaging;
using PlataformaDeGestionDeCursosOnline.Application.DTOs;

namespace PlataformaDeGestionDeCursosOnline.Application.Querys.Estudiantes;

public record ObtenerPerfilEstudiantePorIdQuery(Guid IdEstudiante) : IQuery<EstudianteDTO>;